[build]
builder = "NIXPACKS"

[deploy]
startCommand = "php -S 0.0.0.0:$PORT Index.html"
# O si prefieres usar el servidor PHP estandar que busca index.php:
# startCommand = "php -S 0.0.0.0:$PORT index.php"
