[build]
builder = "NIXPACKS"
buildCommand = "composer install --no-dev --optimize-autoloader && php artisan config:cache"
watchPatterns = ["**/*.php", "composer.json", "composer.lock"]

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
region = "us-east4"
