[build]
builder = "NIXPACKS"
buildCommand = "cd laravel_chat && composer install --no-dev --optimize-autoloader && php artisan config:cache"

[deploy]
startCommand = "cd laravel_chat && php artisan serve --host=0.0.0.0 --port=$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
region = "us-east4"
